name: DrunkOS - ARM64

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
  build_arm64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    -
      name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2
      with:
            image: tonistiigi/binfmt:latest
            platforms: arm64,arm

    - name: Clean up workflow env
      run: |
        # Free up space ( for this workflow )
        # sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(cabal-|dotnet-|ghc-|libmono|php)') \
        # liblldb-6.0 libllvm6.0:amd64 mono-runtime-common monodoc-manual powershell ruby
        
        #sudo apt autoremove -yq
        #sudo rm -rf /opt/hostedtoolcache /usr/local /usr/share/dotnet /usr/share/swift
        
    - name: prepare build env
      run: |
        # Basics
        mkdir -p ~/DRUNK/{docker}
        cd ~/DRUNK
        git clone https://git.it-kuny.ch/drunk/tools.git tools --depth=10

    - name: Setup bootstrap environment
      run: |
        cd ~/DRUNK
        export P_ROOT=$(pwd)

        docker container create \
        --name work01 \
        --volume $P_ROOT:/home/developer/DRUNK \
        --tty \
        --privileged \
        --device=/dev/loop-control:/dev/loop-control \
        --device=/var/run/docker.sock:/var/run/docker.sock \
        --device=/dev/loop0:/dev/loop0 \
        --env PATH=/bin:/sbin:/usr/bin:/usr/sbin \
        --env LD_LIBRARY_PATH=/lib64:/lib:/usr/lib \
        hilledkinged/drunk:aarch64 /bin/bash
        
        # docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

        sleep 1
        echo Started docker
        sudo docker start work01
        # echo " "
        # sudo docker ps -a
        # echo " "
        # sudo docker container logs work01
        sleep 1
        
        sudo docker exec --tty -e PATH=/bin:/sbin:/usr/bin:/usr/sbin work01 /bin/bash -c "bottle -Sy --needed --noconfirm --disable-download-timeout drunk-base systemd util-linux binutils coreutils"

        sudo docker exec --tty -e PATH=/bin:/sbin:/usr/bin:/usr/sbin work01 /bin/bash -c "rm -rf /var/lib/bottle/sync/*"
        sudo docker exec --tty -e PATH=/bin:/sbin:/usr/bin:/usr/sbin work01 /bin/bash -c "useradd developer -m -g wheel"
        sudo docker exec --tty -e PATH=/bin:/sbin:/usr/bin:/usr/sbin work01 /bin/bash -c "bash -c /home/developer/DRUNK/tools/docker/developer.sh"
        sudo docker exec --tty -e PATH=/bin:/sbin:/usr/bin:/usr/sbin work01 /bin/bash -c "bottle -Syu --needed --noconfirm --disable-download-timeout"
        sudo docker exec --tty -e PATH=/bin:/sbin:/usr/bin:/usr/sbin work01 /bin/bash -c "bash -c /home/developer/DRUNK/tools/docker/developer.sh"
        sudo docker exec --tty -e PATH=/bin:/sbin:/usr/bin:/usr/sbin work01 /bin/bash -c "bottle --needed --noconfirm --disable-download-timeout -Sy sudo nano mpfr mpc m4 grep sed gawk drunk-install-scripts"
        sudo docker exec --tty -e PATH=/bin:/sbin:/usr/bin:/usr/sbin work01 /bin/bash -c "bash -c /home/developer/DRUNK/tools/docker/fix_sudo.sh"
        sudo docker exec --tty -e PATH=/bin:/sbin:/usr/bin:/usr/sbin work01 /bin/bash -c "bash -c /home/developer/DRUNK/tools/docker/locale.sh"
        
        sudo docker exec --tty -e PATH=/bin:/sbin:/usr/bin:/usr/sbin work01 /bin/bash -c "chown -R developer /home/developer/DRUNK"

    - name: Pull and install fresh rootfs
      run: |
        # Lets make minimal env with only attr for faster testing times
        sudo docker exec --tty -e PATH=/bin:/sbin:/usr/bin:/usr/sbin work01 /bin/bash -c "cd /home/developer/DRUNK && mkdir -p rootfs"
        sudo docker exec --tty -e PATH=/bin:/sbin:/usr/bin:/usr/sbin work01 /bin/bash -c "cd /home/developer/DRUNK && bottle-strap rootfs drunk-base bottle bash"
      
    - name: Remove old DrunkOS container + image
      run: |
        docker rmi hilledkinged/drunk:aarch64 -f
      
    - name: Tarball and push new image/container
      run: |
        cd ~/DRUNK && sudo tar -C rootfs -c . | sudo docker import - hilledkinged/drunk:aarch64
      
    - name: Login to docker.io
      uses: docker/login-action@v1
      with:
        username: hilledkinged
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Push docker image
      run: |
        docker image push hilledkinged/drunk:aarch64
